---
- name: install kibana(3.0.0)
  unarchive:
    src: https://download.elastic.co/kibana/kibana/kibana-3.0.0.tar.gz
    dest: /etc/
    remote_src: yes
  
- name: config config.js
  lineinfile:
    path: /etc/kibana-3.0.0/config.js
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop: '{{elastic_search}}'
 